# generated by datamodel-codegen:
#   filename:  simple_frozen_test.json
#   timestamp: 1985-10-26T08:21:00+00:00

from __future__ import annotations

from typing import Optional

from attrs import define


@define(kw_only=True, frozen=True)
class User:
    name: str
    age: int
    email: Optional[str] = None
