# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2025-09-01T15:06:12+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional, Union

from attrs import define, field, validators


@define
class AlloyVulnerabilityMetadataInput:
    include: Optional[List[str]] = field(
        metadata={'title': 'Include', 'examples': [[]]}
    )
    exclude: Optional[List[str]] = field(
        metadata={'title': 'Exclude', 'examples': [[]]}
    )
    vulnerability_ids: List[str] = field(
        metadata={
            'description': 'List of vulnerability ids to get metadata for ',
            'title': 'Vulnerability Ids',
        }
    )
    timestamp: Optional[str] = field(
        metadata={
            'description': 'Optional filter for metadata that has been updated since this time',
            'title': 'Timestamp',
        }
    )


class BinaryTermTypesEnum(Enum):
    symbol = 'symbol'
    import_ = 'import'
    export = 'export'


@define
class BulkNormalizeLicenseRequest:
    include: Optional[List[str]] = field(
        metadata={'title': 'Include', 'examples': [[]]}
    )
    exclude: Optional[List[str]] = field(
        metadata={'title': 'Exclude', 'examples': [[]]}
    )
    licenses: List[str] = field(
        validator=[validators.max_len(100)],
        metadata={
            'description': 'The license strings to normalize',
            'title': 'Licenses',
            'examples': [['MIT']],
        },
    )


class DependencyInfoOrigins(Enum):
    """
    Enum that represents the different origins of dependency info that can be queried.
    """

    input = 'input'
    deps_dev = 'deps.dev'


@define
class DownloadUrlResponse:
    download_url: str = field(metadata={'title': 'Download Url'})


@define
class ErrorDetails:
    message: str = field(
        metadata={
            'description': 'A detailed error message.',
            'title': 'Message',
            'examples': ['Resource not found'],
        }
    )


@define
class ErrorResponse:
    status: str = field(
        metadata={
            'description': 'The status of the response.',
            'title': 'Status',
            'examples': ['error'],
        }
    )
    code: int = field(
        metadata={
            'description': 'The HTTP status code of the response.',
            'title': 'Code',
            'examples': [400],
        }
    )
    message: str = field(
        metadata={
            'description': 'A general error message.',
            'title': 'Message',
            'examples': ['Bad request'],
        }
    )
    details: Optional[ErrorDetails] = field(
        metadata={'description': 'Detailed error information if available.'}
    )


class FeatureTypeEnum(Enum):
    file_hash = 'file_hash'
    file_type = 'file_type'
    pkg_hash = 'pkg_hash'
    lib_hash = 'lib_hash'
    import_fuzzy = 'import_fuzzy'
    export_fuzzy = 'export_fuzzy'
    symbol_fuzzy = 'symbol_fuzzy'
    dirent = 'dirent'


@define
class FixedVersion:
    detection: str = field(
        metadata={
            'description': 'CVE associated with package',
            'title': 'Detection',
            'examples': ['CVE-2021-1234'],
        }
    )
    fixed_version: str = field(
        metadata={
            'description': 'Fixed version associated with CVE',
            'title': 'Fixed Version',
            'examples': ['0.9.2'],
        }
    )


@define
class FixedVersionResponse:
    purl: str = field(
        metadata={
            'description': 'Purl associated with software package',
            'title': 'Purl',
            'examples': ['pkg:pypi/aioxmpp@0.9.1'],
        }
    )
    vulnerabilities: Optional[List[FixedVersion]] = field(
        metadata={
            'description': 'CVEs and package version they were fixed.',
            'title': 'Vulnerabilities',
            'examples': [['CVE-2021-1234']],
        }
    )


@define
class FuzzyBinaryTermMatch:
    match_id: str = field(
        metadata={
            'description': 'ID of the matched file in the ground-truth collection',
            'title': 'Match Id',
        }
    )
    matched_term_count: int = field(
        metadata={
            'description': 'Number of terms matched between the input terms and terms in the matched ground-truth file',
            'title': 'Matched Term Count',
        }
    )
    total_document_term_count: int = field(
        metadata={
            'description': 'Total number of terms in the ground-truth file',
            'title': 'Total Document Term Count',
        }
    )
    score: float = field(
        metadata={
            'description': 'Arbitrary score assigned to the match by the underlying matching algorithm',
            'title': 'Score',
        }
    )
    confidence: float = field(
        metadata={
            'description': 'Confidence score of the match (0.0 - 1.0) based on the term intersection',
            'title': 'Confidence',
        }
    )


@define
class FuzzyBinaryTermMatchResponse:
    filtered_input_term_count: int = field(
        metadata={
            'description': 'Total number of unique terms that were queried for after filtering and normalization',
            'title': 'Filtered Input Term Count',
        }
    )
    matches: Optional[List[FuzzyBinaryTermMatch]] = field(
        metadata={
            'description': 'Matches produced for the given input',
            'title': 'Matches',
        }
    )
    message: Optional[str] = field(
        default='Success',
        metadata={
            'description': 'Message providing additional details of the matching process',
            'title': 'Message',
        },
    )


@define
class FuzzyMatchSubcomponentTermsInput:
    terms_by_type: Dict[str, List[str]] = field(
        metadata={
            'description': 'Dictionary where the key is the type term (function/string/etc), and the value is the set of terms to match against the subcomponent ground-truth collection.',
            'title': 'Terms By Type',
            'examples': [
                {
                    'function': ['function_1', 'function_2'],
                    'string': ['string_1', 'string_2'],
                }
            ],
        }
    )
    ids_to_exclude: List[str] = field(
        metadata={
            'description': 'Subcomponent keys to exclude from matching. This is used to iteratively downselect subcomponents.',
            'title': 'Ids To Exclude',
        }
    )


@define
class FuzzySubcomponentTermMatchDetails:
    score: float = field(
        metadata={
            'description': 'Arbitrary score assigned to the match by the underlying matching algorithm',
            'title': 'Score',
        }
    )
    gt_term_count: int = field(
        metadata={
            'description': 'Total number of terms of this type for the given subcomponent in the ground-truth term set',
            'title': 'Gt Term Count',
        }
    )


@define
class GetBulkBody:
    vuln_ids: List[str] = field(
        validator=[validators.min_len(1), validators.max_len(5000)],
        metadata={
            'description': 'List of vulnerability identifiers to retrieve reachability data for.',
            'title': 'Vuln Ids',
            'examples': [['CVE-2013-0268', 'CVE-2012-6548']],
        },
    )


@define
class InputDependency:
    """
    Input model for a software component dependency
    """

    from_: str = field(
        metadata={
            'description': "PURL of the component that has a dependency on the 'to' component. This PURL must appear in the 'components' section.",
            'title': 'From',
        }
    )
    to: str = field(
        metadata={
            'description': "PURL of the component that is depended on by the 'from'component. This PURL must appear in the 'components' section.",
            'title': 'To',
        }
    )


@define
class IsPatchedInput:
    """
    IsPatched Input
    """

    major_version: str = field(
        metadata={
            'description': 'Major version',
            'title': 'Major Version',
            'examples': ['openSUSE Leap 15.4'],
        }
    )
    cve: str = field(
        metadata={
            'description': 'CVE name',
            'title': 'Cve',
            'examples': ['CVE-2022-42325'],
        }
    )
    purl: str = field(
        metadata={
            'description': 'Package URL',
            'title': 'Purl',
            'examples': ['pkg:rpm/xen@4.16.5_06-150400.4.37.1'],
        }
    )


@define
class IsPatchedResponse:
    """
    IsPatched Response
    """

    status: str = field(
        metadata={
            'description': 'Status of the CVE',
            'title': 'Status',
            'examples': ['affected', 'not affected', 'unknown'],
        }
    )
    cve: str = field(
        metadata={
            'description': 'CVE name',
            'title': 'Cve',
            'examples': ['CVE-2022-42325'],
        }
    )
    purl: str = field(
        metadata={
            'description': 'Package URL',
            'title': 'Purl',
            'examples': ['pkg:rpm/xen@4.16.5_06-150400.4.37.1'],
        }
    )
    fixed_in: Dict[str, str] = field(
        metadata={
            'description': 'Fixed in which patch',
            'title': 'Fixed In',
            'examples': [{'patch': 'SUSE-SLE-Module-Server-12-SP5-2021-1234-1'}],
        }
    )
    patch_info: str = field(
        metadata={
            'description': 'Patch information',
            'title': 'Patch Info',
            'examples': ['Security update for libsolv, libzypp, zypper'],
        }
    )
    vendor_status: str = field(
        metadata={
            'description': 'Vendor status',
            'title': 'Vendor Status',
            'examples': ['will not fix', 'end of life', 'released'],
        }
    )


@define
class KernelModuleMetadataRequestInput:
    """
    Kernel Module Metadata Request Input
    """

    module_name: str = field(
        metadata={
            'description': 'Name of the kernel module to retrieve metadata for.',
            'title': 'Module Name',
        }
    )
    module_file_path: Optional[str] = field(
        metadata={
            'description': 'Path to the kernel module file to retrieve metadata for. If provided, this is used to disambiguate between multiple modules with the same name.',
            'title': 'Module File Path',
        }
    )
    module_description: Optional[str] = field(
        metadata={
            'description': 'Description of the kernel module to retrieve metadata for. If provided, this is used to disambiguate between multiple modules with the same name.',
            'title': 'Module Description',
        }
    )
    kernel_version: Optional[str] = field(
        metadata={
            'description': 'Kernel version to retrieve metadata for. For now this field is ignored, but in the future this will be used to retrieve version-specific metadata when available.',
            'title': 'Kernel Version',
        }
    )


@define
class KernelModuleMetadataResponse:
    """
    Kernel Module Metadata Expected Response
    """

    name: str = field(
        metadata={
            'description': 'Name of the kernel module',
            'title': 'Name',
            'examples': ['page_alloc'],
        }
    )
    source_files: List[str] = field(
        metadata={
            'description': 'Source file paths (relative to the kernel repo root) that contribute logic to the kernel module',
            'title': 'Source Files',
            'examples': ['kernel/mm/page_alloc.c'],
        }
    )
    config_options: Dict[str, str] = field(
        metadata={
            'description': 'Kernel config options that are required for this module to included in a kernel',
            'title': 'Config Options',
            'examples': ['CONFIG_SMP'],
        }
    )
    makefile_path: str = field(
        metadata={
            'description': 'Path to the Makefile that contains the kernel module make target',
            'title': 'Makefile Path',
            'examples': ['kernel/mm/Makefile'],
        }
    )
    license: Optional[str] = field(
        metadata={
            'description': 'Raw license string specified by the kernel module, if specified',
            'title': 'License',
            'examples': ['GPL'],
        }
    )
    description: Optional[str] = field(
        metadata={
            'description': 'Description of the kernel module, if specified',
            'title': 'Description',
            'examples': ['Page allocation module'],
        }
    )
    authors: Optional[List[str]] = field(
        metadata={
            'description': 'Authors of the kernel module, if specified',
            'title': 'Authors',
            'examples': [['Linus Torvalds <linus@linux.com>']],
        }
    )
    version: Optional[str] = field(
        metadata={
            'description': 'Version of the kernel module, if specified by the module itself',
            'title': 'Version',
            'examples': ['1.0.0'],
        }
    )
    aliases: Optional[List[str]] = field(
        metadata={
            'description': 'Aliases of the kernel module, if specified',
            'title': 'Aliases',
            'examples': [['foo', 'bar']],
        }
    )
    source_licenses: Optional[List[str]] = field(
        metadata={
            'description': 'SPDX license identifiers from source files that contribute to the kernel module',
            'title': 'Source Licenses',
            'examples': [['GPL-2.0', 'MIT']],
        }
    )
    concluded_license: Optional[str] = field(
        metadata={
            'description': 'Final SPDX license expression of the kernel module concluded by Finite State based on the available information',
            'title': 'Concluded License',
            'examples': ['GPL-2.0-only AND MIT'],
        }
    )
    kernel_version: str = field(
        metadata={
            'description': 'Kernel version that this module metadata applies to',
            'title': 'Kernel Version',
            'examples': ['6.15.0'],
        }
    )


@define
class LimitOffsetPageStr:
    items: List[str] = field(metadata={'title': 'Items'})
    total: Optional[int] = field(metadata={'title': 'Total'})
    limit: Optional[int] = field(metadata={'title': 'Limit'})
    offset: Optional[int] = field(metadata={'title': 'Offset'})


@define
class MergebasePackageMetadataResponse:
    purl: str = field(
        metadata={
            'description': 'Package URL that the given metadata applies to.',
            'title': 'Purl',
            'examples': ['pkg:generic/foobar@1.2.3'],
        }
    )
    r: str = field(
        metadata={'description': 'The architecture e.g. NPM, PYPI', 'title': 'R'}
    )
    g: Optional[str] = field(
        metadata={'description': 'The group id/namespace if applicable', 'title': 'G'}
    )
    a: str = field(
        metadata={
            'description': 'The artifact id or name, e.g. openssl or requests',
            'title': 'A',
        }
    )
    v: str = field(
        metadata={'description': 'The version string e.g. 1.2.3', 'title': 'V'}
    )
    q: Optional[str] = field(
        metadata={'description': 'The qualifiers string if applicable', 'title': 'Q'}
    )
    s: Optional[str] = field(
        metadata={'description': 'The subpath if applicable', 'title': 'S'}
    )
    hash: Optional[str] = field(
        metadata={'description': 'Component Hash', 'title': 'Hash'}
    )
    releaseDate: Optional[str] = field(
        metadata={
            'description': 'Date the component was released',
            'title': 'Releasedate',
        }
    )
    openSource: Optional[bool] = field(
        metadata={
            'description': 'Whether the component is open source',
            'title': 'Opensource',
        }
    )
    projectHomepage: Optional[str] = field(
        metadata={
            'description': 'Homepage of the component package',
            'title': 'Projecthomepage',
        }
    )
    licenseInfo: List[str] = field(
        metadata={
            'description': 'List of SPDX license identifiers',
            'title': 'Licenseinfo',
        }
    )
    updated: str = field(
        metadata={
            'description': 'Timestamp the component was last updated in our system',
            'title': 'Updated',
        }
    )
    verified: bool = field(
        metadata={
            'description': 'Whether the component is verified, not used',
            'title': 'Verified',
        }
    )
    subComponents: List[str] = field(
        metadata={
            'description': 'List of subcomponents, not used',
            'title': 'Subcomponents',
        }
    )


@define
class MergebaseVulnerability:
    id: str = field(metadata={'description': 'The vulnerability ID', 'title': 'Id'})
    cvssV1: Optional[float] = field(
        metadata={'description': 'The CVSS V1 score', 'title': 'Cvssv1'}
    )
    cvssV2: Optional[float] = field(
        metadata={'description': 'The CVSS V2.0 Score', 'title': 'Cvssv2'}
    )
    cvssV3: Optional[float] = field(
        metadata={'description': 'The CVSS V3.0 Score', 'title': 'Cvssv3'}
    )
    cvssV31: Optional[float] = field(
        metadata={'description': 'The CVSS V3.1 Score', 'title': 'Cvssv31'}
    )
    cvssV4: Optional[float] = field(
        metadata={'description': 'The CVSS V4.0 Score', 'title': 'Cvssv4'}
    )
    cweSet: List[str] = field(
        metadata={'description': 'Set of CWE IDs', 'title': 'Cweset'}
    )
    jvnId: Optional[str] = field(
        metadata={'description': 'The JVN ID', 'title': 'Jvnid'}
    )
    jvnUrl: Optional[str] = field(
        metadata={'description': 'The JVN URL', 'title': 'Jvnurl'}
    )
    exploitMaturity: Optional[str] = field(
        metadata={'description': 'The Exploit Maturity', 'title': 'Exploitmaturity'}
    )
    epssScore: Optional[float] = field(
        metadata={'description': 'The EPSS Score', 'title': 'Epssscore'}
    )
    epssPercentile: Optional[float] = field(
        metadata={'description': 'The EPSS Percentile', 'title': 'Epsspercentile'}
    )


@define
class NormalizedLicenseResponse:
    input_expression: str = field(
        metadata={
            'description': 'Input license expression',
            'title': 'Input Expression',
            'examples': ['MIT and (gplv2+ with eCos-2.0 or foobar license)'],
        }
    )
    translated_expression: str = field(
        metadata={
            'description': 'Translated license expression',
            'title': 'Translated Expression',
            'examples': ['MIT AND (GPL-2.0-or-later WITH eCos-2.0 OR foobar license)'],
        }
    )
    spdx_compliant: bool = field(
        metadata={
            'description': 'SPDX compliant flag',
            'title': 'Spdx Compliant',
            'examples': [False],
        }
    )
    license_metadata: List[Dict[str, Any]] = field(
        metadata={
            'description': 'License metadata',
            'title': 'License Metadata',
            'examples': [
                {'raw_value': 'MIT', 'spdx_id': 'MIT'},
                {
                    'raw_value': 'gplv2+ with eCos-2.0',
                    'spdx_id': 'GPL-2.0-or-later WITH eCos-2.0',
                },
                {'raw_value': 'foobar license'},
            ],
        }
    )


class OperatingSystemDistro(Enum):
    """
    Enumeration of operating system distributions.
    """

    alpine = 'alpine'
    debian = 'debian'
    openSUSE = 'openSUSE'
    redhat = 'redhat'
    suse = 'suse'
    ubuntu = 'ubuntu'


@define
class PackageMetadata:
    purl: str = field(
        metadata={
            'description': 'The Package URL (PURL) that was given in the request.',
            'title': 'Purl',
            'examples': ['pkg:generic/foobar@1.2.3'],
        }
    )
    matched_purl: str = field(
        metadata={
            'description': 'The Package URL (PURL) that was matched in the database.',
            'title': 'Matched Purl',
            'examples': ['pkg:generic/foobar@1.2.3'],
        }
    )
    cdx: Dict[str, Any] = field(
        metadata={
            'description': 'The Common Data Model (CDX) metadata for the package.',
            'title': 'Cdx',
        }
    )
    fs: Dict[str, Any] = field(
        metadata={
            'description': 'Field containing additional Finite State-specific data that was captured but does not align with the CDX specification.',
            'title': 'Fs',
        }
    )
    generated_fields: Optional[List[str]] = field(
        metadata={
            'description': 'The fields that were generated for the metadata.',
            'title': 'Generated Fields',
            'examples': ['license'],
        }
    )
    timestamp: str = field(
        metadata={
            'description': 'The timestamp of the metadata.',
            'title': 'Timestamp',
            'examples': ['2021-01-01T00:00:00'],
        }
    )
    sources: Optional[List[str]] = field(
        metadata={
            'description': 'The sources of the metadata.',
            'title': 'Sources',
            'examples': ['NVD', 'VulnDB'],
        }
    )


@define
class PackageMetadataInput:
    """
    Package Metadata Expected Input
    """

    purl: Union[str, List[str]] = field(
        metadata={
            'description': 'Package url (purl) associated with software package',
            'title': 'Purl',
            'examples': ['pkg:pypi/aioxmpp@0.9.1'],
        }
    )
    use_fuzzy_matching: Optional[bool] = field(
        metadata={'title': 'Use Fuzzy Matching', 'examples': [False]}
    )


@define
class PackageMetadataResponse:
    """
    Package Metadata Expected Response
    """

    purl: str = field(
        metadata={
            'description': 'Purl associated with software package',
            'title': 'Purl',
            'examples': ['pkg:pypi/aioxmpp@0.9.1'],
        }
    )
    licenses: Optional[List[str]] = field(
        metadata={
            'description': 'License associated with this purl',
            'title': 'Licenses',
            'examples': [['LGPL-3.0-or-later']],
        }
    )
    matches: Optional[List[Dict[str, Any]]] = field(
        metadata={
            'description': 'License matches',
            'title': 'Matches',
            'examples': [[{'LGPL-3.0-or-later': 0.8}]],
        }
    )
    confidence: Optional[float] = field(
        metadata={
            'description': 'Confidence of the match',
            'title': 'Confidence',
            'examples': ['0.8'],
        }
    )
    is_eol: bool = field(
        metadata={
            'description': 'Whether software package is currently in End of life status',
            'title': 'Is Eol',
            'examples': [True],
        }
    )
    eol_date: Optional[str] = field(
        metadata={
            'description': 'End of life date (if known)',
            'title': 'Eol Date',
            'examples': ['2022-01-01'],
        }
    )
    research_attributes: Optional[Dict[str, Any]] = field(
        metadata={
            'description': 'Research attributes associated with this purl',
            'title': 'Research Attributes',
        }
    )


@define
class PackageMetadataV2Response:
    purl: str = field(
        metadata={
            'description': 'Package URL that the given metadata applies to.',
            'title': 'Purl',
            'examples': ['pkg:generic/foobar@1.2.3'],
        }
    )
    metadata: Dict[str, Any] = field(
        metadata={
            'description': 'Metadata for the given PURL. This is guaranteed to contain all of the required fields (license, supplier_name, homepage, description), although their values may be null. It may also contain additional information beyond the required fields.',
            'title': 'Metadata',
            'examples': [
                {
                    'description': 'A test package.',
                    'homepage': 'https://acme.com',
                    'license': 'MIT',
                    'other_field': 'Another bit of metadata.',
                    'supplier_name': 'Acme, Inc.',
                }
            ],
        }
    )
    generated_fields: List[str] = field(
        metadata={
            'description': 'List of non-null fields that were generated by an AI model instead of being looked up from a source of ground-truth or provided in the query itself.',
            'title': 'Generated Fields',
            'examples': [['license', 'homepage', 'description']],
        }
    )


@define
class PackageVersionResponse:
    """
    Package Version Model
    """

    purl: str = field(metadata={'description': 'Package URL', 'title': 'Purl'})
    publishedAt: str = field(
        metadata={
            'description': 'Date and time the package was published at',
            'title': 'Publishedat',
        }
    )
    isDefault: bool = field(
        metadata={
            'description': 'Is this package version the default version?',
            'title': 'Isdefault',
        }
    )
    isDeprecated: bool = field(
        metadata={
            'description': 'Is this package version deprecated?',
            'title': 'Isdeprecated',
        }
    )
    vulnerabilities: List[Dict[str, Any]] = field(
        metadata={'description': 'List of vulnerabilities', 'title': 'Vulnerabilities'}
    )
    risk: Optional[float] = field(
        metadata={'description': 'Risk of package version', 'title': 'Risk'}
    )
    popularity: Optional[int] = field(
        metadata={'description': 'Popularity of package version', 'title': 'Popularity'}
    )
    compatability: Optional[int] = field(
        metadata={
            'description': 'Compatability of package version, an integer between 0 and 100',
            'title': 'Compatability',
        }
    )


@define
class PackagesForFeatureValuesResult:
    feature_value_pkgs: Optional[Dict[str, List[str]]] = field(
        metadata={
            'description': 'A dictionary where the keys are feature values and the values are lists of packages that contain that feature value',
            'title': 'Feature Value Pkgs',
        }
    )
    max_cardinality_exceeded: Optional[List[str]] = field(
        metadata={
            'description': 'List of feature values that exceeded the specified max cardinality (AKA the ones that belong to too many packages)',
            'title': 'Max Cardinality Exceeded',
        }
    )


@define
class Pagination:
    total: int = field(
        metadata={
            'description': 'The total number of items.',
            'title': 'Total',
            'examples': [100],
        }
    )
    page: int = field(
        metadata={
            'description': 'The current page number.',
            'title': 'Page',
            'examples': [1],
        }
    )
    size: int = field(
        metadata={
            'description': 'The number of items per page.',
            'title': 'Size',
            'examples': [10],
        }
    )
    total_pages: int = field(
        metadata={
            'description': 'The total number of pages.',
            'title': 'Total Pages',
            'examples': [10],
        }
    )


@define
class PaginationParams:
    page: Optional[int] = field(
        default=1,
        validator=[validators.ge(1)],
        metadata={'description': 'Page number, starts from 1', 'title': 'Page'},
    )
    size: Optional[int] = field(
        default=10,
        validator=[validators.ge(1), validators.le(100)],
        metadata={'description': 'Number of items per page (1-100)', 'title': 'Size'},
    )


@define
class PatchResponse:
    """
    Patch Response
    """

    patch: str = field(
        metadata={
            'description': 'Patch name',
            'title': 'Patch',
            'examples': ['SUSE-SLE-Module-Server-12-SP5-2021-1234-1'],
        }
    )
    cves: List[str] = field(
        metadata={
            'description': 'CVEs remediated with following patch',
            'title': 'Cves',
            'examples': [['CVE-2021-1234', 'CVE-2021-5678']],
        }
    )
    tracking: List[Dict[str, Any]] = field(
        metadata={
            'description': 'Tracking information for patch',
            'title': 'Tracking',
            'examples': [{'status': 'released'}],
        }
    )
    references: List[List[Dict[str, Any]]] = field(
        metadata={
            'description': 'References for patch',
            'title': 'References',
            'examples': [[{'URL': 'https://www.suse.com/security/cve/CVE-2021-1234/'}]],
        }
    )
    title: List[str] = field(
        metadata={
            'description': 'Titles of fixes including in the patch name',
            'title': 'Title',
            'examples': [
                'Security update for libsolv, libzypp, zypper',
                'Security update for python-M2Crypto',
            ],
        }
    )


@define
class ReachabilityInfo:
    vuln_id: str = field(metadata={'title': 'Vuln Id'})
    vuln_functions: Optional[List[str]] = field(metadata={'title': 'Vuln Functions'})
    kernel_modules: Optional[List[str]] = field(metadata={'title': 'Kernel Modules'})


@define
class RelatedPackagesRequest:
    include: Optional[List[str]] = field(
        metadata={'title': 'Include', 'examples': [[]]}
    )
    exclude: Optional[List[str]] = field(
        metadata={'title': 'Exclude', 'examples': [[]]}
    )
    purls: List[str] = field(
        metadata={
            'description': 'The Package URLs (PURLs) to lookup.',
            'title': 'Purls',
            'examples': [['pkg:generic/foobar@1.2.3']],
        }
    )


@define
class RemediationGuidanceInput:
    """
    Input model for the /remediation_guidance
    """

    purls: List[str] = field(
        metadata={
            'description': 'List of PURLs to get remediation guidance for',
            'title': 'Purls',
        }
    )


@define
class RequestManyByVulnIdSet:
    include: Optional[List[str]] = field(
        metadata={'title': 'Include', 'examples': [[]]}
    )
    exclude: Optional[List[str]] = field(
        metadata={'title': 'Exclude', 'examples': [[]]}
    )
    vuln_id_set: List[str] = field(
        metadata={
            'title': 'List of vulnerability IDs to query',
            'examples': [['CVE-2003-0425', 'CVE-2015-5951']],
        }
    )


@define
class ResolveDepsInput:
    """
    Input model for the /resolve_dependencies endpoint
    """

    components: List[str] = field(
        metadata={
            'description': 'List of PURLs to resolve dependencies for',
            'title': 'Components',
        }
    )
    dependencies: List[InputDependency] = field(
        metadata={
            'description': 'List of known dependencies between the given components',
            'title': 'Dependencies',
        }
    )


@define
class ResponseComponent:
    """
    Response model for a software component
    """

    purl: str = field(
        metadata={'description': 'Package URL for the component', 'title': 'Purl'}
    )
    added: bool = field(
        metadata={
            'description': "True if the component was added based on dependency info (AKA it didn't apear in the input set of components)",
            'title': 'Added',
        }
    )
    deps_known: bool = field(
        metadata={
            'description': 'True if ground-truth dependency info was found for this component, even if the component has no dependencies.',
            'title': 'Deps Known',
        }
    )


@define
class ResponseDependency:
    """
    Response model for a software component dependency
    """

    from_: str = field(
        metadata={
            'description': "PURL of the component that has a dependency on the 'to' component.",
            'title': 'From',
        }
    )
    to: str = field(
        metadata={
            'description': "PURL of the component that is depended on by the 'from'component.",
            'title': 'To',
        }
    )
    constraint: str = field(
        metadata={
            'description': "Version constraint for the dependency. May be 'Unknown' if not known.",
            'title': 'Constraint',
        }
    )
    origin: DependencyInfoOrigins = field(
        metadata={'description': 'Origin/source of the dependency information'}
    )
    added: bool = field(
        metadata={
            'description': "True if the dependency was added based on dependency info (AKA it didn't apear in the input set of dependencies)",
            'title': 'Added',
        }
    )
    updated: bool = field(
        metadata={
            'description': 'True if the dependency was updated based on dependency info (e.g. the version constraint was changed)',
            'title': 'Updated',
        }
    )
    errors: List[str] = field(
        metadata={
            'description': 'List of errors that occurred while trying to create this dependency. This may be empty. This will most often occur when our internal version constraint parsers fails to parse info from the upstream dependency information source.',
            'title': 'Errors',
        }
    )


@define
class ResponsePackageMetadata:
    status: str = field(
        metadata={
            'description': 'The status of the response.',
            'title': 'Status',
            'examples': ['OK', 'Created'],
        }
    )
    code: int = field(
        metadata={
            'description': 'The HTTP status code of the response.',
            'title': 'Code',
            'examples': [200, 201],
        }
    )
    data: PackageMetadata = field(
        metadata={'description': 'The data returned by the API.'}
    )
    pagination: Optional[Pagination] = field(
        metadata={'description': 'Pagination details if applicable.'}
    )
    warnings: Optional[List[str]] = field(
        metadata={
            'description': 'A list of warnings about this response',
            'title': 'Warnings',
        }
    )
    message: Optional[str] = field(
        default='',
        metadata={
            'description': 'A message describing the response.',
            'title': 'Message',
        },
    )


@define
class ResponseReachabilityInfo:
    status: str = field(
        metadata={
            'description': 'The status of the response.',
            'title': 'Status',
            'examples': ['OK', 'Created'],
        }
    )
    code: int = field(
        metadata={
            'description': 'The HTTP status code of the response.',
            'title': 'Code',
            'examples': [200, 201],
        }
    )
    data: ReachabilityInfo = field(
        metadata={'description': 'The data returned by the API.'}
    )
    pagination: Optional[Pagination] = field(
        metadata={'description': 'Pagination details if applicable.'}
    )
    warnings: Optional[List[str]] = field(
        metadata={
            'description': 'A list of warnings about this response',
            'title': 'Warnings',
        }
    )
    message: Optional[str] = field(
        default='',
        metadata={
            'description': 'A message describing the response.',
            'title': 'Message',
        },
    )


@define
class ResponseListReachabilityInfo:
    status: str = field(
        metadata={
            'description': 'The status of the response.',
            'title': 'Status',
            'examples': ['OK', 'Created'],
        }
    )
    code: int = field(
        metadata={
            'description': 'The HTTP status code of the response.',
            'title': 'Code',
            'examples': [200, 201],
        }
    )
    data: List[ReachabilityInfo] = field(
        metadata={'description': 'The data returned by the API.', 'title': 'Data'}
    )
    pagination: Optional[Pagination] = field(
        metadata={'description': 'Pagination details if applicable.'}
    )
    warnings: Optional[List[str]] = field(
        metadata={
            'description': 'A list of warnings about this response',
            'title': 'Warnings',
        }
    )
    message: Optional[str] = field(
        default='',
        metadata={
            'description': 'A message describing the response.',
            'title': 'Message',
        },
    )


@define
class ResponseListDict:
    status: str = field(
        metadata={
            'description': 'The status of the response.',
            'title': 'Status',
            'examples': ['OK', 'Created'],
        }
    )
    code: int = field(
        metadata={
            'description': 'The HTTP status code of the response.',
            'title': 'Code',
            'examples': [200, 201],
        }
    )
    data: List[Dict[str, Any]] = field(
        metadata={'description': 'The data returned by the API.', 'title': 'Data'}
    )
    pagination: Optional[Pagination] = field(
        metadata={'description': 'Pagination details if applicable.'}
    )
    warnings: Optional[List[str]] = field(
        metadata={
            'description': 'A list of warnings about this response',
            'title': 'Warnings',
        }
    )
    message: Optional[str] = field(
        default='',
        metadata={
            'description': 'A message describing the response.',
            'title': 'Message',
        },
    )


@define
class SPDXLicenseLite:
    """
    SPDX License Response
    """

    license_name: Optional[str] = field(
        metadata={
            'description': 'SPDX license name',
            'title': 'License Name',
            'examples': ['389-exception'],
        }
    )
    license_id: Optional[str] = field(
        metadata={
            'description': 'SPDX license identifier',
            'title': 'License Id',
            'examples': ['389-exception'],
        }
    )
    name: Optional[str] = field(
        metadata={
            'description': 'SPDX license name',
            'title': 'Name',
            'examples': ['GNU Affero General Public License v1.0'],
        }
    )
    url: Optional[str] = field(
        metadata={
            'description': 'SPDX license details url',
            'title': 'Url',
            'examples': ['https://spdx.org/licenses/AGPL-1.0.html'],
        }
    )
    category: Optional[str] = field(
        metadata={
            'description': 'SPDX license category',
            'title': 'Category',
            'examples': ['Permissive'],
        }
    )
    is_exception: Optional[bool] = field(
        metadata={
            'description': 'Is this a license exception?',
            'title': 'Is Exception',
            'examples': [False],
        }
    )
    license_exception_id: Optional[str] = field(
        metadata={
            'description': 'SPDX license exception identifier',
            'title': 'License Exception Id',
            'examples': ['AGPL-1.0'],
        }
    )


@define
class SPDXResponse:
    """
    SPDX License Expected Response
    """

    license_id: str = field(
        metadata={
            'description': 'SPDX license identifier',
            'title': 'License Id',
            'examples': ['389-exception'],
        }
    )
    license_exception_id: Optional[str] = field(
        metadata={
            'description': 'SPDX license exception identifier',
            'title': 'License Exception Id',
            'examples': ['AGPL-1.0'],
        }
    )
    reference: str = field(
        metadata={
            'description': 'SPDX license reference',
            'title': 'Reference',
            'examples': ['https://spdx.org/licenses/AGPL-1.0.html'],
        }
    )
    name: str = field(
        metadata={
            'description': 'SPDX license name',
            'title': 'Name',
            'examples': ['GNU Affero General Public License v1.0'],
        }
    )
    is_deprecated_license: bool = field(
        metadata={
            'description': 'Is deprecated license identifier',
            'title': 'Is Deprecated License',
            'examples': [False],
        }
    )
    details_url: str = field(
        metadata={
            'description': 'SPDX license details url',
            'title': 'Details Url',
            'examples': ['https://spdx.org/licenses/AGPL-1.0.html'],
        }
    )
    reference_number: Optional[int] = field(
        metadata={
            'description': 'SPDX license reference number',
            'title': 'Reference Number',
            'examples': [1],
        }
    )
    is_osi_approved: bool = field(
        metadata={
            'description': 'Is OSI approved',
            'title': 'Is Osi Approved',
            'examples': [True],
        }
    )
    is_fsf_libre: bool = field(
        metadata={
            'description': 'Is FSF libre',
            'title': 'Is Fsf Libre',
            'examples': [True],
        }
    )
    see_also: Optional[List[str]] = field(
        metadata={
            'description': 'SPDX license see also',
            'title': 'See Also',
            'examples': [['https://spdx.org/licenses/AGPL-1.0.html']],
        }
    )
    copy_left: str = field(
        metadata={
            'description': 'SPDX license copy left',
            'title': 'Copy Left',
            'examples': ['Network'],
        }
    )


class SoftwareIdType(Enum):
    """
    Software identifier types supported for generation
    """

    cpe = 'cpe'
    purl = 'purl'


@define
class SoftwareInfo:
    """
    Software component metadata used for generating software identifiers.
    """

    name: str = field(
        metadata={
            'description': 'Name of software component',
            'title': 'Name',
            'examples': ['busybox'],
        }
    )
    version: str = field(
        metadata={
            'description': 'Version of software component',
            'title': 'Version',
            'examples': ['1.2.5'],
        }
    )
    supplier_name: Optional[str] = field(
        metadata={
            'description': 'Optional name of software component supplier',
            'title': 'Supplier Name',
            'examples': ['debian'],
        }
    )
    supplier_type: Optional[str] = field(
        metadata={
            'description': "Optional type of the software component, such as 'rpm' or 'deb'",
            'title': 'Supplier Type',
            'examples': ['deb'],
        }
    )
    generate_purl_only: Optional[bool] = field(
        metadata={
            'description': 'Optional boolean indicating whether to generate purl only for the given component',
            'title': 'Generate Purl Only',
        }
    )
    purl: Optional[str] = field(
        metadata={
            'description': 'Optional purl to use for the given component. If provided, this will be for CPE lookups.',
            'title': 'Purl',
            'examples': [None],
        }
    )


class SubcomponentTermTypesEnum(Enum):
    function = 'function'
    string = 'string'


@define
class ValidationError:
    loc: List[Union[str, int]] = field(metadata={'title': 'Location'})
    msg: str = field(metadata={'title': 'Message'})
    type: str = field(metadata={'title': 'Error Type'})


@define
class VersionKey:
    r: str = field(
        metadata={'description': 'The architecture e.g. NPM, PYPI', 'title': 'R'}
    )
    a: str = field(
        metadata={
            'description': 'The artifact id or name, e.g. openssl or requests',
            'title': 'A',
        }
    )
    v: str = field(
        metadata={'description': 'The version string e.g. 1.2.3', 'title': 'V'}
    )
    g: Optional[str] = field(
        default='',
        metadata={'description': 'The namespace or group id. optional', 'title': 'G'},
    )
    q: Optional[str] = field(
        default='',
        metadata={'description': 'The qualifiers string, optional', 'title': 'Q'},
    )
    s: Optional[str] = field(
        default='', metadata={'description': 'The subpath, optional', 'title': 'S'}
    )


class VulnMatchSoftwareIdType(Enum):
    """
    Software Identifier types supported for vulnerability matching
    """

    cpe = 'cpe'
    purl = 'purl'


class VulnMatchSources(Enum):
    """
    Supported sources for vulnerability matches
    """

    internal_0 = 'internal_0'
    external_0 = 'external_0'


@define
class BulkPackageMetadataRequest:
    include: Optional[List[str]] = field(
        metadata={'title': 'Include', 'examples': [[]]}
    )
    exclude: Optional[List[str]] = field(
        metadata={'title': 'Exclude', 'examples': [[]]}
    )
    purls: List[str] = field(
        validator=[validators.max_len(100)],
        metadata={
            'description': 'The Package URLs (PURLs) to lookup.',
            'title': 'Purls',
            'examples': [['pkg:pypi/requests@1.2.3']],
        },
    )
    timestamp: Optional[str] = field(
        metadata={
            'description': 'If the metadata has not been updated after this timestamp, it will not be returned',
            'title': 'Timestamp',
            'examples': ['2021-01-01T00:00:00'],
        }
    )
    pagination: Optional[PaginationParams] = field(
        metadata={
            'description': 'The pagination details for the request.',
            'examples': [{'page': 1, 'size': 10}],
        }
    )
    enable_fuzzy_matching: Optional[bool] = field(
        default=False,
        metadata={
            'description': 'Whether to enable fuzzy matching. Defaults to False. Enabling this will increase response times, sometimes dramatically, depending on how many of the givne PURLs have exact matches in the database. Use with caution!',
            'title': 'Enable Fuzzy Matching',
            'examples': [True],
        },
    )


@define
class FuzzySubcomponentTermMatch:
    subcomponent_id: str = field(
        metadata={
            'description': 'Key of the matched subcomponent in the ground-truth collection',
            'title': 'Subcomponent Id',
        }
    )
    name: str = field(
        metadata={
            'description': 'Name of the subcomponent that was matched',
            'title': 'Name',
        }
    )
    version: str = field(
        metadata={
            'description': 'Version of the matched subcomponent',
            'title': 'Version',
        }
    )
    total_score: float = field(
        metadata={
            'description': 'Total score of the match (sum of scores for each term type)',
            'title': 'Total Score',
        }
    )
    match_details_by_type: Dict[str, FuzzySubcomponentTermMatchDetails] = field(
        metadata={
            'description': 'Details of the match for each term type',
            'title': 'Match Details By Type',
            'examples': [
                {
                    'function': {'gt_term_count': 10, 'score': 532.1},
                    'string': {'gt_term_count': 10, 'score': 532.1},
                }
            ],
        }
    )


@define
class FuzzySubcomponentTermMatchResponse:
    input_term_counts_by_type: Dict[str, int] = field(
        metadata={
            'description': 'Number of input terms for each term type',
            'title': 'Input Term Counts By Type',
            'examples': [{'function': 3, 'string': 3}],
        }
    )
    matches: Optional[List[FuzzySubcomponentTermMatch]] = field(
        metadata={
            'description': 'Matches produced for the given input',
            'title': 'Matches',
        }
    )
    message: Optional[str] = field(
        default='Success',
        metadata={
            'description': 'Message providing additional details of the matching process',
            'title': 'Message',
        },
    )


@define
class HTTPValidationError:
    detail: Optional[List[ValidationError]] = field(metadata={'title': 'Detail'})


@define
class LimitOffsetPagePatchResponse:
    items: List[PatchResponse] = field(metadata={'title': 'Items'})
    total: Optional[int] = field(metadata={'title': 'Total'})
    limit: Optional[int] = field(metadata={'title': 'Limit'})
    offset: Optional[int] = field(metadata={'title': 'Offset'})


@define
class MergebasePackageVulnerabilitiesResponse:
    purl: str = field(
        metadata={
            'description': 'Package URL that the given metadata applies to.',
            'title': 'Purl',
            'examples': ['pkg:generic/foobar@1.2.3'],
        }
    )
    r: str = field(
        metadata={'description': 'The architecture e.g. NPM, PYPI', 'title': 'R'}
    )
    g: Optional[str] = field(
        metadata={'description': 'The group id/namespace if applicable', 'title': 'G'}
    )
    a: str = field(
        metadata={
            'description': 'The artifact id or name, e.g. openssl or requests',
            'title': 'A',
        }
    )
    v: str = field(
        metadata={'description': 'The version string e.g. 1.2.3', 'title': 'V'}
    )
    q: Optional[str] = field(
        metadata={'description': 'The qualifiers string if applicable', 'title': 'Q'}
    )
    s: Optional[str] = field(
        metadata={'description': 'The subpath if applicable', 'title': 'S'}
    )
    hash: Optional[str] = field(
        metadata={'description': 'SHA256 hash', 'title': 'Hash'}
    )
    cveSet: List[MergebaseVulnerability] = field(
        metadata={'description': 'Set of CVEs', 'title': 'Cveset'}
    )


@define
class PackageResponse:
    """
    Package Response Model (contains many versions)
    """

    purl: str = field(metadata={'description': 'Package URL', 'title': 'Purl'})
    versions: List[PackageVersionResponse] = field(
        metadata={'description': 'List of package versions', 'title': 'Versions'}
    )


@define
class ResolveDepsResponse:
    """
    Response model for the /resolve_dependencies endpoint
    """

    components: List[ResponseComponent] = field(
        metadata={
            'description': 'List of software components and metadata about them, including ones that were added based on dependency info',
            'title': 'Components',
        }
    )
    dependencies: List[ResponseDependency] = field(
        metadata={
            'description': 'List of dependency information, including ones that were added based on dependency info',
            'title': 'Dependencies',
        }
    )


@define
class ResponseListSPDXLicenseLite:
    status: str = field(
        metadata={
            'description': 'The status of the response.',
            'title': 'Status',
            'examples': ['OK', 'Created'],
        }
    )
    code: int = field(
        metadata={
            'description': 'The HTTP status code of the response.',
            'title': 'Code',
            'examples': [200, 201],
        }
    )
    data: List[SPDXLicenseLite] = field(
        metadata={'description': 'The data returned by the API.', 'title': 'Data'}
    )
    pagination: Optional[Pagination] = field(
        metadata={'description': 'Pagination details if applicable.'}
    )
    warnings: Optional[List[str]] = field(
        metadata={
            'description': 'A list of warnings about this response',
            'title': 'Warnings',
        }
    )
    message: Optional[str] = field(
        default='',
        metadata={
            'description': 'A message describing the response.',
            'title': 'Message',
        },
    )


@define
class SoftwareId:
    """
    Software identifier information generated for given software component metadata.
    """

    type: SoftwareIdType = field(
        metadata={'description': 'Type of software identifier'}
    )
    value: str = field(
        metadata={'description': 'Value of software identifier', 'title': 'Value'}
    )
    confidence: float = field(
        validator=[validators.ge(0), validators.le(1)],
        metadata={
            'description': 'Confidence that this identifier correctly represents the given software component.',
            'title': 'Confidence',
        },
    )
    gt_match: Optional[bool] = field(
        metadata={
            'description': 'True if the value exactly matches a known ground-truth software identifier. Null if unknown or unverified.',
            'title': 'Gt Match',
        }
    )


@define
class VulnMatchSoftwareId:
    """
    Software Identifier information used for matching vulnerabilities
    """

    type: VulnMatchSoftwareIdType = field(
        metadata={'description': 'Type of software identifier'}
    )
    value: str = field(
        metadata={
            'description': 'Value of software identifier. Must be valid for the given type.',
            'title': 'Value',
            'examples': ['cpe:2.3:a:apache:log4j:2.0:-:*:*:*:*:*:*'],
        }
    )
    confidence: Optional[float] = field(
        default=1.0,
        validator=[validators.ge(0), validators.le(1)],
        metadata={
            'description': 'Confidence that this software identifier being valid for the BOM under test. This is used when determining overall vulnerability match confidence. If not specified, the confidence is assumed to be 1.0.',
            'title': 'Confidence',
            'examples': [0.9],
        },
    )


@define
class MatchedVulnerability:
    ids: List[str] = field(
        metadata={
            'description': "Vulnerability IDs. This is a list because a vulnerability may have multiple IDs or 'aliases' (such as CVE and GHSA identifiers). All IDs in this list are assumed to represent the same underlying vulnerability.",
            'title': 'Ids',
            'examples': [['CVE-2021-44228', 'GHSA-jfh8-c2jp-5v3q']],
        }
    )
    confidence: float = field(
        validator=[validators.ge(0), validators.le(1)],
        metadata={
            'description': 'The overall confidence that this vulnerability applies to the given set of software IDs',
            'title': 'Confidence',
            'examples': [0.9],
        },
    )
    sources: List[VulnMatchSources] = field(
        metadata={
            'description': 'Sources of this vulnerability match',
            'title': 'Sources',
        }
    )
    affected_software_ids: List[VulnMatchSoftwareId] = field(
        metadata={
            'description': 'Software IDs affected by this vulnerability',
            'title': 'Affected Software Ids',
        }
    )
    cache: Optional[bool] = field(
        default=True,
        metadata={
            'description': 'Whether or not to Cache this vulnerability match',
            'title': 'Cache',
        },
    )


@define
class AlloyVulnerabilityMatchResponse:
    status: str = field(
        metadata={
            'description': 'The status of the response.',
            'title': 'Status',
            'examples': ['success'],
        }
    )
    code: int = field(
        metadata={
            'description': 'The HTTP status code of the response.',
            'title': 'Code',
            'examples': [200],
        }
    )
    data: List[MatchedVulnerability] = field(
        metadata={
            'description': 'Vulnerability Matches for Software Identifiers.',
            'title': 'Data',
            'examples': [
                {
                    'affected_software_ids': [
                        {
                            'confidence': 1,
                            'type': 'purl',
                            'value': 'pkg:pypi/requests@1.2.3',
                        }
                    ],
                    'confidence': 1,
                    'cwes': ['CWE-123'],
                    'id': 'CVE-2018-18074',
                    'sources': ['external_0'],
                }
            ],
        }
    )
    message: Optional[str] = field(
        default='Vulnerability Matches retrieved successfully',
        metadata={
            'description': 'A message describing the response.',
            'title': 'Message',
        },
    )
